version: '3.4'
services:
  postgres:
    container_name: social-site-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: socialsite
      POSTGRES_DB: socialsite
      
volumes:
  postgres_data: